#!/bin/bash

# Mine

set -e

restore_configs

export V1_VERSION=${V1_VERSION}D

$CFGDIR/common/v1-base-config
$CFGDIR/common/cnc-config
$CFGDIR/boards/skr_pro
$CFGDIR/accessories/tmc2209
$CFGDIR/accessories/TFT35_e3_v3_CNC
$CFGDIR/accessories/dual-drivers-on-xy
$CFGDIR/boards/skr_pro_dual
$CFGDIR/accessories/laser

opt_add SPINDLE_LASER_PWM_PIN PF9
opt_add SPINDLE_LASER_ENA_PIN PB0


opt_set X_DRIVER_TYPE  "TMC2209"
opt_set Y_DRIVER_TYPE  "TMC2209"
opt_set Z_DRIVER_TYPE  "TMC2209"
opt_set X2_DRIVER_TYPE  "TMC2209"
opt_set Y2_DRIVER_TYPE  "TMC2209"

opt_set X2_CURRENT 900
opt_set Y2_CURRENT 900

opt_disable \
    E0_DRIVER_TYPE

# CUSTOM SETTINGS FOR MY CNC MACHINE
# Inverse the Z motor.
opt_set INVERT_Z_DIR "true"
# Enable Adafruit Lib for RBG Strip
opt_add NEOPIXEL_LED
opt_set NEOPIXEL_PIN PC9
# NEO_GRBW, NEO_RGBW, NEO_GRB, NEO_RBG, etc.
opt_set NEOPIXEL_TYPE "NEO_GRB"
opt_set NEOPIXEL_PIXELS "118"
opt_set NEOPIXEL_BRIGHTNESS "255"

# Make sure Z_MIN_ENDSTOP is open
opt_set Z_MIN_ENDSTOP_HIT_STATE "LOW"
opt_set Z_MIN_PROBE_ENDSTOP_HIT_STATE "LOW"

opt_set X_BED_SIZE "600"
opt_set Y_BED_SIZE "600"
opt_set Z_MAX_POS "100"

opt_set MAX_SOFTWARE_ENDSTOPS

export PLATFORMIO_ENV=BIGTREE_SKR_PRO
